/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mandelag.app.motd;

import akka.NotUsed;
import akka.actor.ActorRef;
import akka.actor.ActorSystem;
import akka.http.javadsl.ConnectHttp;
import akka.http.javadsl.Http;
import akka.http.javadsl.ServerBinding;
import akka.http.javadsl.model.HttpEntities;
import akka.http.javadsl.model.HttpRequest;
import akka.http.javadsl.model.HttpResponse;
import akka.http.javadsl.model.RequestEntity;
import akka.http.javadsl.server.Route;
import akka.pattern.Patterns;
import akka.stream.ActorMaterializer;
import akka.stream.javadsl.Flow;

import java.io.IOException;
import java.time.Duration;
import java.util.concurrent.CompletionStage;

import static akka.http.javadsl.server.Directives.*;

public class App {
  public static void main(String[] args) throws IOException {
    ActorSystem system = ActorSystem.create("routes");
    ActorSystem motdSystem = ActorSystem.create("motd-system");

    final ActorMaterializer materializer = ActorMaterializer.create(system);

    final ActorRef motdHandler = motdSystem.actorOf(MotdActor.props(
        "Mantap!",
        "It always seems impossible until it is done.",
        "Sughoi!",
        "Always program to an interface, not to an implementation.",
        "Strategy pattern!"
    ));

    final Http http = Http.get(system);

    final Flow<HttpRequest, HttpResponse, NotUsed> routes = appRoute(motdHandler).flow(system, materializer);
    final CompletionStage<ServerBinding> binding = http.bindAndHandle(routes, ConnectHttp.toHost("0.0.0.0", 8080), materializer);

    System.out.println("Server started...");
    System.in.read();

    binding.thenCompose(ServerBinding::unbind)
        .thenAccept(unbound -> system.terminate());
  }

  public static Route appRoute(ActorRef handler) {
    return path("", () ->
        concat(
            get(() -> {
              CompletionStage<RequestEntity> reply = Patterns.ask(handler, new MotdActor.GetMotd(), Duration.ofMillis(50))
                  .thenApply(obj -> obj.toString())
                  .thenApply(str -> HttpEntities.create(str));
              return completeOKWithFuture(reply);
            }),
            post(() -> formField("message", str -> {
              handler.tell(new MotdActor.AddMotd(str), ActorRef.noSender());
              return complete("OKEOCE");
            }))
        )
    );
  }
}
